module EvolutionaryDecisionTrees

include("requirements.jl")

include("types/global.jl")
include("types/classification/nodes.jl")
include("types/classification/tree.jl")
include("types/classification/metrics.jl")

include("functions/genetics.jl")
include("functions/plot.jl")


include("mlj/mlj.jl")

export
  AccuracyFitness,
  BalancedAccuracyFitness,
  BinaryF1ScoreFitness,
  ChildDirection,
  ClassificationTree,
  ClassificationTreeNode,
  ConstraintDict,
  DepthPenalty,
  DeterministicEvolutionaryDecisionTreeClassifier,
  FitnessMetric,
  InformednessFitness,
  LabelDict,
  LeafDistribution,
  LeafLabel,
  LeftChild,
  MarkednessFitness,
  MatthewsCorrelationFitness,
  MultiF1ScoreFitness,
  NodeConstraints,
  NodeMap,
  NodePenalty,
  OptionalClassificationNode,
  PenaltyType,
  PlotClassifierTree,
  RefValue,
  RightChild,
  TargetType,
  AbstractTreeNode,
  attributes,
  attrlabel,
  attrlabels,
  branch,
  child!,
  childdir,
  create_attribute_randomiser,
  create_constraints_generator,
  create_decision_randomiser,
  create_empty_constraints_generator,
  create_left_constraints_generator,
  create_nodemap,
  create_outcome_randomiser,
  create_parent_constraints_generator,
  create_right_constraints_generator,
  crossover,
  evaluate_fitness,
  evolve,
  fitness,
  informedness,
  isbranch,
  isleaf,
  isleftchild,
  isrightchild,
  isroot,
  leaf,
  left,
  leftchild!,
  markedness,
  merge,
  metric_function,
  mutate!,
  nodelevel,
  nodenumber,
  outcome_class_predictions,
  outcome_probability_predictions,
  outcomelabel,
  parent,
  penalised_fitness,
  plotclassifiertree,
  plotclassifiertree!,
  prune,
  prune!,
  random_classification_tree,
  random_classification_trees,
  reset_nodemap!,
  right,
  rightchild!,
  subtree,
  train,
  treeplot,
  walk_tree!

end
